// <auto-generated />
using System;
using EXE_BE.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE_BE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320131228_AddFriendship")]
    partial class AddFriendship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EXE_BE.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EarnedCoins")
                        .HasColumnType("int");

                    b.Property<int>("EarnedExp")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("FocusSessions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.GameItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPremiumOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PriceCoins")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("GameItems");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.RoomCharacter", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VirtualRoomId")
                        .HasColumnType("char(36)");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("CharacterId");

                    b.HasIndex("UserId");

                    b.HasIndex("VirtualRoomId");

                    b.ToTable("RoomCharacters");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.StudyRoom", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoomId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("StudyRooms");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.StudyRoomMember", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoomId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("StudyRoomMembers");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowsPremiumCosmetics")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("RemovesAds")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PackageId");

                    b.ToTable("SubscriptionPackages");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserCoinTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoinTransactions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserItemPosition", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoomMode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VirtualRoomId")
                        .HasColumnType("char(36)");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("PositionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("VirtualRoomId");

                    b.ToTable("UserItemPositions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserPurchase", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CoinsSpent")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPurchases");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SubscriptionPackagePackageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("SubscriptionPackagePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.VirtualRoom", b =>
                {
                    b.Property<Guid>("VirtualRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("VirtualRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("VirtualRooms");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.FocusSession", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.StudyRoom", "Room")
                        .WithMany("FocusSessions")
                        .HasForeignKey("RoomId");

                    b.HasOne("EXE_BE.Domain.Entities.Topic", "Topic")
                        .WithMany("FocusSessions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("FocusSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "Friend")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.RoomCharacter", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("RoomCharacters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.VirtualRoom", "VirtualRoom")
                        .WithMany("Characters")
                        .HasForeignKey("VirtualRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VirtualRoom");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.StudyRoom", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedRooms")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.StudyRoomMember", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.StudyRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("JoinedRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.Topic", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserCoinTransaction", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("CoinTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserItem", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.GameItem", "Item")
                        .WithMany("UserItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserItemPosition", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.GameItem", "Item")
                        .WithMany("ItemPositions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("ItemPositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.VirtualRoom", "VirtualRoom")
                        .WithMany("ItemPositions")
                        .HasForeignKey("VirtualRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Item");

                    b.Navigation("User");

                    b.Navigation("VirtualRoom");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserPurchase", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.GameItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPackagePackageId");

                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.VirtualRoom", b =>
                {
                    b.HasOne("EXE_BE.Domain.Entities.User", "User")
                        .WithMany("VirtualRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.GameItem", b =>
                {
                    b.Navigation("ItemPositions");

                    b.Navigation("Purchases");

                    b.Navigation("UserItems");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.StudyRoom", b =>
                {
                    b.Navigation("FocusSessions");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.Topic", b =>
                {
                    b.Navigation("FocusSessions");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.User", b =>
                {
                    b.Navigation("CoinTransactions");

                    b.Navigation("CreatedRooms");

                    b.Navigation("FocusSessions");

                    b.Navigation("ItemPositions");

                    b.Navigation("JoinedRooms");

                    b.Navigation("Purchases");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("RoomCharacters");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("Subscriptions");

                    b.Navigation("Topics");

                    b.Navigation("UserItems");

                    b.Navigation("VirtualRooms");
                });

            modelBuilder.Entity("EXE_BE.Domain.Entities.VirtualRoom", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ItemPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
